/* Electron entrypoint and access-portal renderer for Mediator 2. */
if (typeof require === "function" && typeof module !== "undefined" && module.exports) {
  const { app, BrowserWindow, ipcMain, safeStorage, shell } = require("electron");
  const fs = require("node:fs/promises");
  const path = require("node:path");

  const hasLock = app.requestSingleInstanceLock();
  if (!hasLock) {
    app.quit();
  } else {
    let window;
    const credentialFile = () => path.join(app.getPath("userData"), "bridge-access.json");
    const createWindow = () => {
      window = new BrowserWindow({
        width: 1320, height: 820, minWidth: 760, minHeight: 620,
        frame: false, backgroundColor: "#08090b", show: false,
        webPreferences: { preload: path.join(__dirname, "preload.js"), contextIsolation: true, nodeIntegration: false }
      });
      window.loadFile("index.html");
      window.once("ready-to-show", () => window.show());
    };
    app.on("second-instance", () => { if (window) { if (window.isMinimized()) window.restore(); window.focus(); } });
    app.whenReady().then(() => {
      ipcMain.handle("window:minimize", () => window?.minimize());
      ipcMain.handle("window:maximize", () => window?.isMaximized() ? window.unmaximize() : window?.maximize());
      ipcMain.handle("window:close", () => window?.close());
      ipcMain.handle("external:open", (_, url) => shell.openExternal(url));
      ipcMain.handle("credentials:load", async () => {
        try {
          const saved = JSON.parse(await fs.readFile(credentialFile(), "utf8"));
          if (!safeStorage.isEncryptionAvailable()) return null;
          return { ...saved, token: safeStorage.decryptString(Buffer.from(saved.token, "base64")) };
        } catch { return null; }
      });
      ipcMain.handle("credentials:save", async (_, credentials) => {
        if (!safeStorage.isEncryptionAvailable()) throw new Error("Operating-system credential encryption is unavailable.");
        const saved = { ...credentials, token: safeStorage.encryptString(credentials.token).toString("base64") };
        await fs.writeFile(credentialFile(), JSON.stringify(saved), { mode: 0o600 });
      });
      ipcMain.handle("credentials:clear", async () => { await fs.rm(credentialFile(), { force: true }); });
      createWindow();
    });
    app.on("window-all-closed", () => app.quit());
  }
} else {
  const $ = (selector) => document.querySelector(selector);
  const desktop = window.mediatorDesktop;
  const form = $("#loginForm");
  let sessionBridge = null;
  let universe = null;
  let currentPage = "home";
  const fallbackImages = {
    character: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85",
    location: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=85",
    map: "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1400&q=85"
  };
  const demoArchive = {
    version: 4,
    identity: { name: "The Astral Verge", genre: "Science fantasy · Age of Embers", description: "A dying constellation bound together by ancient gates, wandering cities, and the people who remember how the stars once spoke.", image: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=1800&q=90" },
    characters: [
      { id:"c1", name:"Ilyra Voss", subtitle:"Keeper of the Last Gate", meta:"ARCHIVE 01", origin:"Asterfall", image:"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1000&q=85", description:"An exile carrying a map written in light, Ilyra can hear the dormant gates beneath every city." },
      { id:"c2", name:"Orin Vale", subtitle:"Celestial Cartographer", meta:"ARCHIVE 02", origin:"The Drift", image:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1000&q=85", description:"Orin charts paths through impossible space and erases every route that leads back to his past." },
      { id:"c3", name:"Sera Nox", subtitle:"Ember Envoy", meta:"ARCHIVE 03", origin:"Veyra Prime", image:"https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1000&q=85", description:"A diplomat whose calm voice conceals the last living spark of a vanished sun." }
    ],
    locations: [
      { id:"l1", name:"Asterfall", subtitle:"The Vertical City", meta:"CAPITAL", origin:"Cinder Reach", image:"https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1400&q=85", description:"A city suspended around a broken star-gate, where every district follows a different gravity." },
      { id:"l2", name:"The Glass Expanse", subtitle:"Shattered moon desert", meta:"REGION", origin:"Veyra Prime", image:"https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1400&q=85", description:"A silver desert that preserves the reflections of everyone who crosses it." }
    ],
    maps: [{ id:"m1", name:"The Cinder Reach", subtitle:"Primary stellar chart", meta:"7 MARKERS", origin:"Astral Verge", image:"https://images.unsplash.com/photo-1446776877081-d282a0f896e2?auto=format&fit=crop&w=1600&q=85", description:"The known passageways between the seven surviving systems." }],
    modules: [{id:"timeline",name:"Chronicle",description:"Layer eras, events, and turning points across your universe.",status:"COMING SOON"},{id:"relations",name:"Constellation",description:"See characters, factions, and places as a living relationship network.",status:"COMING SOON"},{id:"languages",name:"Lexicon",description:"Build languages, scripts, naming systems, and translations.",status:"IN DEVELOPMENT"}]
  };
  const escapeHTML = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
  const pluralFor = (type) => type === "map" ? "maps" : `${type}s`;
  const img = (item, type) => `<img src="${escapeHTML(item.image || fallbackImages[type])}" alt="${escapeHTML(item.name)}" onerror="this.src='${fallbackImages[type]}'">`;
  const toast = (message) => { const el=$("#workspaceToast"); el.textContent=message; el.classList.add("show"); setTimeout(()=>el.classList.remove("show"),2200); };
  const motionEnabled = !matchMedia("(prefers-reduced-motion: reduce)").matches;
  const title=$(".split-title"); title.innerHTML=`<span class="word" style="--i:0">Every</span> <span class="word" style="--i:1">world</span><br><span class="word" style="--i:2">begins</span> <span class="word" style="--i:3">with</span> <span class="word" style="--i:4">a</span> <em class="word" style="--i:5">door.</em>`;
  if (motionEnabled) {
    const canvas=$("#starfield"), ctx=canvas.getContext("2d"); let stars=[];
    const resize=()=>{ const d=Math.min(devicePixelRatio||1,2); canvas.width=innerWidth*d; canvas.height=innerHeight*d; ctx.setTransform(d,0,0,d,0,0); stars=Array.from({length:110},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,s:Math.random()*1.4+.3})); };
    const draw=()=>{ctx.clearRect(0,0,innerWidth,innerHeight); stars.forEach(s=>{s.y-=s.s*.05;if(s.y<0)s.y=innerHeight;ctx.fillStyle=`rgba(217,255,99,${.08+s.s*.12})`;ctx.fillRect(s.x,s.y,s.s,s.s)});requestAnimationFrame(draw)}; resize();draw();addEventListener("resize",resize);
    document.addEventListener("pointermove",e=>{const aura=$(".cursor-aura");aura.style.transform=`translate3d(${e.clientX-17}px,${e.clientY-17}px,0)`;document.documentElement.style.setProperty("--mx",`${e.clientX/innerWidth*100}%`);document.documentElement.style.setProperty("--my",`${e.clientY/innerHeight*100}%`)});
  }
  const request = async (path, credentials, options={}) => { const response=await fetch(`https://api.github.com${path}`,{...options,headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${credentials.token}`,"X-GitHub-Api-Version":"2022-11-28",...options.headers}}); if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message||`GitHub rejected the request (${response.status}).`)} return response.status===204?null:response.json(); };
  const connectBridge = async credentials => { const base=`/repos/${encodeURIComponent(credentials.owner)}/${encodeURIComponent(credentials.repo)}`; const repository=await request(base,credentials); let archive={version:4,identity:{name:credentials.repo,description:"A universe waiting to be discovered."},characters:[],locations:[],maps:[],modules:demoArchive.modules}; try{const file=await request(`${base}/contents/mediator/data.json`,credentials);archive=JSON.parse(decodeURIComponent(escape(atob(file.content.replace(/\\n/g,"")))))}catch(error){if(!/Not Found/i.test(error.message))throw error} return{repository,archive,credentials}; };
  const persist = async message => { if(sessionBridge?.demo){toast(message||"CHANGES SAVED FOR THIS DEMO SESSION");return} toast("SAVING TO BRIDGE…"); try { const {credentials,repository}=sessionBridge, base=`/repos/${encodeURIComponent(credentials.owner)}/${encodeURIComponent(credentials.repo)}/contents/mediator/data.json`; let sha; try{sha=(await request(base,credentials)).sha}catch(e){if(!/Not Found/i.test(e.message))throw e} const content=btoa(unescape(encodeURIComponent(JSON.stringify({...universe,version:4,updatedAt:new Date().toISOString()},null,2)))); await request(base,credentials,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:"Update Mediator universe archive",content,branch:repository.default_branch,...(sha&&{sha})})});toast(message||"UNIVERSE SAVED") } catch(error){toast(`SAVE FAILED · ${error.message}`)} };
  const navItems=[['home','⌂','Home'],['characters','◉','Characters'],['locations','⌖','Locations'],['universe','✦','Universe'],['tools','＋','Tools']];
  const windowControls=()=>`<div class="workspace-window-actions"><button data-window="minimize" aria-label="Minimize window">—</button><button data-window="maximize" aria-label="Maximize window">□</button><button class="close" data-window="close" aria-label="Close window">×</button></div>`;
  const shell=()=>{$("#workspace").innerHTML=`<div class="workspace-drag"></div><aside class="console-rail"><div class="brand"><span class="brand-mark"><i></i><i></i><i></i></span><span>MEDIATOR <b>2</b></span></div><nav>${navItems.map(([id,icon,label])=>`<button data-page="${id}" aria-label="${label}"><i>${icon}</i><span>${label}</span></button>`).join('')}</nav><div class="rail-status"><i></i><span>${sessionBridge.demo?'LOCAL DEMO':'BRIDGE ONLINE'}</span><small>${escapeHTML(sessionBridge.repository.full_name)}</small></div></aside><main class="console-main"><header class="console-top"><div><small>ACTIVE UNIVERSE</small><strong>${escapeHTML(universe.identity.name)}</strong></div><div class="console-clock"><span id="liveClock"></span><button data-action="command" aria-label="Open quick actions">⌘ K</button>${windowControls()}</div></header><section id="workspaceView" class="workspace-view"></section></main>`; setInterval(()=>{const c=$("#liveClock");if(c)c.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})},1000);};
  const stat=(value,label)=>`<div class="universe-stat"><strong>${value}</strong><span>${label}</span></div>`;
  const homeView=()=>{const i=universe.identity;$("#workspaceView").innerHTML=`<section class="home-hero">${img(i,'map')}<div class="hero-shade"></div><div class="hero-code">UNIVERSE // ${escapeHTML(i.genre||'UNCLASSIFIED')}</div><div class="hero-copy"><span class="edition">WELCOME BACK, ARCHITECT</span><h1>${escapeHTML(i.name)}</h1><p>${escapeHTML(i.description)}</p><button class="primary-button" data-page="universe">ENTER UNIVERSE →</button></div><div class="hero-stats">${stat(universe.characters.length,'CHARACTERS')}${stat(universe.locations.length + universe.maps.length,'PLACES')}</div></section><div class="section-head"><div><span class="edition">CONTINUE BUILDING</span><h2>Your universe is in motion.</h2></div><small>SELECT AN ARCHIVE TO EXPAND</small></div><div class="archive-launchers">${[['characters','◉','People & identities',universe.characters.length],['locations','⌖','Maps, zones & places',universe.locations.length+universe.maps.length],['universe','✦','Identity & canon',1],['tools','＋','Optional systems',universe.modules.length]].map(([p,ic,sub,count],n)=>`<button data-page="${p}"><span>0${n+1}</span><i>${ic}</i><div><strong>${p.toUpperCase()}</strong><small>${sub}</small></div><b>${count}</b><em>→</em></button>`).join('')}</div>`};
  const archiveView=(type)=>{const plural=pluralFor(type),items=universe[plural]||[],label=plural.toUpperCase();$("#workspaceView").innerHTML=`<header class="archive-heading"><div><span class="edition">${label} // ${String(items.length).padStart(2,'0')} ENTRIES</span><h1>${type==='character'?'People shape every world.':'Every place holds a story.'}</h1><p>Build rich profiles, then connect them across your living universe.</p></div><button class="primary-button" data-create="${type}">＋ NEW ${type.toUpperCase()}</button></header>${items.length?`<div class="cinematic-grid">${items.map(item=>`<article class="cinematic-card" data-detail="${type}:${item.id}">${img(item,type)}<div><span>${escapeHTML(item.meta||'ARCHIVE ENTRY')}</span><h2>${escapeHTML(item.name)}</h2><p>${escapeHTML(item.subtitle||item.origin||'Unclassified')}</p></div><i>EXPLORE →</i></article>`).join('')}<button class="create-card" data-create="${type}"><b>＋</b><span>ADD TO ${label}</span></button></div>`:`<div class="empty-universe"><div><div class="empty-orb">＋</div><h2>Discover your first ${type}.</h2><p>Start with a name. The details can emerge later.</p><button class="primary-button" data-create="${type}">CREATE ENTRY →</button></div></div>`}`};
  const locationsView=()=>{const maps=universe.maps||[], places=universe.locations||[]; const children=parent=>places.filter(x=>x.origin===parent); $("#workspaceView").innerHTML=`<header class="archive-heading location-heading"><div><span class="edition">WORLD ATLAS // ${maps.length+places.length} NODES</span><h1>One atlas. Every layer.</h1><p>Define a map, nest zones inside it, then place cities, landmarks, and locations inside those zones.</p></div><div class="location-actions"><button class="ghost-button" data-create="map">＋ MAP</button><button class="primary-button" data-create="location">＋ ZONE / LOCATION</button></div></header><div class="atlas-toolbar"><div class="atlas-tabs"><button class="active">HIERARCHY</button><button>ATLAS VIEW</button><button>UNASSIGNED <b>${places.filter(x=>!x.origin).length}</b></button></div><span>MAP → ZONE → LOCATION</span></div><section class="atlas-layout"><div class="atlas-tree"><header><span>LOCATION HIERARCHY</span><small>Drag-ready logical structure</small></header>${maps.map((map,n)=>`<div class="tree-map"><button data-detail="map:${map.id}"><i>⌖</i><span><strong>${escapeHTML(map.name)}</strong><small>MAP · ${escapeHTML(map.meta||'WORLD')}</small></span><b>${children(map.name).length}</b></button>${children(map.name).map(zone=>`<div class="tree-zone"><button data-detail="location:${zone.id}"><i>◇</i><span><strong>${escapeHTML(zone.name)}</strong><small>${escapeHTML(zone.meta||'ZONE')}</small></span></button>${children(zone.name).map(place=>`<button class="tree-place" data-detail="location:${place.id}"><i>•</i><span><strong>${escapeHTML(place.name)}</strong><small>LOCATION</small></span></button>`).join('')}</div>`).join('')}</div>`).join('')}${places.filter(x=>!x.origin||(!maps.some(m=>m.name===x.origin)&&!places.some(p=>p.name===x.origin))).map(x=>`<button class="tree-loose" data-detail="location:${x.id}"><i>◇</i><span><strong>${escapeHTML(x.name)}</strong><small>UNASSIGNED</small></span></button>`).join('')}</div><div class="atlas-preview">${maps[0]?img(maps[0],'map'):''}<div class="atlas-overlay"><span>ACTIVE WORLD LAYER</span><h2>${escapeHTML(maps[0]?.name||'Create your first map')}</h2><p>${escapeHTML(maps[0]?.description||'Your atlas begins with a visual foundation.')}</p><div class="map-pins"><i style="--x:28%;--y:34%">1</i><i style="--x:62%;--y:56%">2</i><i style="--x:76%;--y:27%">3</i></div></div></div></section>`};
  const detailView=(type,id)=>{const item=(universe[pluralFor(type)]||[]).find(x=>x.id===id);if(!item)return type==='character'?archiveView(type):locationsView(); const connected=type==='character'?universe.locations.filter(l=>l.name===item.origin):universe.characters.filter(c=>c.origin===item.name); if(type==='character'){const level=parseInt(item.meta?.match(/\d+/)?.[0]||'42',10);$("#workspaceView").innerHTML=`<button class="back-link" data-page="characters">← CHARACTER ROSTER</button><section class="rpg-sheet"><div class="rpg-art">${img(item,type)}<div class="rpg-scan"></div><span>ACTIVE HERO // ${escapeHTML(item.id)}</span></div><div class="rpg-data"><header><div><span class="edition">CHARACTER DOSSIER</span><h1>${escapeHTML(item.name)}</h1><h3>${escapeHTML(item.subtitle||'Unclassified')}</h3></div><div class="level-medallion"><small>LEVEL</small><strong>${String(level).padStart(2,'0')}</strong><i></i></div></header><div class="xp-label"><span>ASCENSION PROGRESS</span><b>78%</b></div><div class="xp-gauge"><i></i></div><div class="vitals"><article><span>VITALITY</span><strong>8,420</strong><i style="--v:86%"></i></article><article><span>FOCUS</span><strong>6,180</strong><i style="--v:72%"></i></article><article><span>RENOWN</span><strong>LEGENDARY</strong><i style="--v:92%"></i></article></div><div class="rpg-lore"><small>ORIGIN</small><strong>${escapeHTML(item.origin||'Unknown realm')}</strong><p>${escapeHTML(item.description||'No lore has been recorded yet.')}</p></div><div class="ability-grid"><article><i>✦</i><span>GATE SENSE</span><b>MASTERED</b></article><article><i>◈</i><span>ASTRAL WARD</span><b>RANK VII</b></article><article><i>⌁</i><span>VOID STEP</span><b>RANK V</b></article></div><div class="profile-actions"><button class="primary-button" data-edit="character:${item.id}">EDIT LOADOUT</button><button class="ghost-button danger" data-delete="character:${item.id}">ARCHIVE</button></div></div></section>`;return} $("#workspaceView").innerHTML=`<button class="back-link" data-page="locations">← WORLD ATLAS</button><section class="codex-profile"><div class="codex-art">${img(item,type)}<span>${escapeHTML(item.meta||'ARCHIVE ENTRY')}</span></div><div class="codex-copy"><span class="edition">${type.toUpperCase()} CODEX // ${escapeHTML(item.id)}</span><h1>${escapeHTML(item.name)}</h1><h3>${escapeHTML(item.subtitle||'Unclassified')}</h3><div class="codex-rule"></div><small>PARENT MAP / ZONE</small><strong>${escapeHTML(item.origin||'Not yet connected')}</strong><p>${escapeHTML(item.description||'No lore has been recorded yet.')}</p><div class="profile-actions"><button class="primary-button" data-edit="${type}:${item.id}">EDIT ENTRY</button><button class="ghost-button danger" data-delete="${type}:${item.id}">ARCHIVE</button></div>${connected.length?`<div class="linked-entries"><span>CONNECTED ENTRIES</span>${connected.map(x=>`<b>${escapeHTML(x.name)}</b>`).join('')}</div>`:''}</div></section>`};
  const universeView=()=>{const i=universe.identity;$("#workspaceView").innerHTML=`<section class="identity-page"><div class="identity-art">${img(i,'map')}</div><div class="identity-copy"><span class="edition">UNIVERSE IDENTITY</span><h1>${escapeHTML(i.name)}</h1><h3>${escapeHTML(i.genre||'Genre and era unwritten')}</h3><p>${escapeHTML(i.description)}</p><div class="identity-totals">${stat(universe.characters.length,'CHARACTERS')}${stat(universe.locations.length+universe.maps.length,'PLACES')}</div><button class="primary-button" data-action="edit-universe">EDIT UNIVERSE IDENTITY</button></div></section>`};
  const toolsView=()=>{$("#workspaceView").innerHTML=`<header class="archive-heading"><div><span class="edition">SYSTEM LIBRARY // MODULE FRAMEWORK</span><h1>Expand only when you choose.</h1><p>Your core universe stays simple. Modules add specialized systems without crowding your creative space.</p></div><div class="catalog-status"><i></i> CATALOGUE SYNCHRONIZED</div></header><nav class="tool-tabs"><button class="active">DISCOVER</button><button>INSTALLED <b>0</b></button><button>UPDATES <b>0</b></button></nav><div class="module-feature"><div><span class="edition">MODULE SYSTEM // READY</span><h2>New dimensions are on the horizon.</h2></div><strong>CORE v2.0<br><small>COMPATIBLE</small></strong></div><div class="module-grid">${universe.modules.map((m,n)=>`<article><span>0${n+1} // ${m.status}</span><i>${['⌁','◎','Aa'][n]}</i><h3>${m.name}</h3><p>${m.description}</p><button disabled>NOTIFY WHEN READY</button></article>`).join('')}</div>`};
  const navigate=(page,detail)=>{currentPage=page;document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(detail){const [type,id]=detail;detailView(type,id)}else if(page==='home')homeView();else if(page==='characters')archiveView('character');else if(page==='locations')locationsView();else if(page==='universe')universeView();else toolsView();$(".console-main")?.scrollTo({top:0,behavior:'smooth'});};
  const openModal=(type,id='')=>{const isUniverse=type==='universe',item=isUniverse?universe.identity:(id?(universe[pluralFor(type)]||[]).find(x=>x.id===id):null),f=$("#entityForm");f.reset();f.elements.type.value=type;f.elements.id.value=id;$("#entityModalTitle").textContent=isUniverse?'Edit universe identity':`${id?'Edit':'Create'} ${type}`;$("#entityModalLabel").textContent=isUniverse?'UNIVERSE IDENTITY':`${type.toUpperCase()} ARCHIVE`;$("#subtitleField").firstChild.textContent=isUniverse?'GENRE / ERA':type==='location'?'TYPE':'TITLE';$("#metaField").firstChild.textContent=isUniverse?'EDITION':type==='character'?'LEVEL':'STATUS';$("#originField").firstChild.textContent=isUniverse?'TAGLINE':type==='character'?'ORIGIN':'PARENT MAP / ZONE';if(item){f.elements.name.value=item.name||'';f.elements.subtitle.value=isUniverse?(item.genre||''):(item.subtitle||'');f.elements.meta.value=item.meta||'';f.elements.origin.value=item.origin||'';f.elements.image.value=item.image||'';f.elements.description.value=item.description||'';f.elements.gallery.value=(item.gallery||[]).join('\n')}$("#entityModal").hidden=false;setTimeout(()=>f.elements.name.focus(),30)};
  const enter=(archive,session)=>{sessionBridge=session;universe={identity:{name:'Untitled Universe'},characters:[],locations:[],maps:[],modules:demoArchive.modules,...archive};universe.modules||=demoArchive.modules;shell();$("#workspace").hidden=false;$("#success").hidden=true;navigate('home')};
  form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const button=$("#submitButton"),credentials={owner:$("#owner").value.trim(),repo:$("#repo").value.trim(),token:$("#token").value.trim()};button.classList.add('loading');try{const session=await connectBridge(credentials);if($("#remember").checked)await desktop?.saveCredentials(credentials);$("#successTitle").textContent=`Welcome, ${credentials.owner}.`;$("#successMessage").textContent=`${session.repository.full_name} is ready`;$("#success").hidden=false;setTimeout(()=>enter(session.archive,session),700)}catch(error){$("#errorBox").textContent=error.message;$("#errorBox").hidden=false}finally{button.classList.remove('loading')}});
  $("#demoButton").addEventListener('click',()=>{const archive=JSON.parse(JSON.stringify(demoArchive));enter(archive,{demo:true,repository:{full_name:'LOCAL / THE-ASTRAL-VERGE'}})});
  $("#reveal").addEventListener('click',()=>{$("#token").type=$("#token").type==='password'?'text':'password'});$("#minimize").addEventListener('click',()=>desktop?.minimize());$("#maximize").addEventListener('click',()=>desktop?.maximize());$("#closeWindow").addEventListener('click',()=>desktop?.close());$("#tokenHelp").addEventListener('click',e=>{if(desktop){e.preventDefault();desktop.openExternal(e.currentTarget.href)}});$("#forgetButton").addEventListener('click',async()=>{await desktop?.clearCredentials();form.reset()});
  document.addEventListener('click',e=>{const win=e.target.closest('[data-window]');if(win){desktop?.[win.dataset.window]?.();return}const page=e.target.closest('[data-page]'),detail=e.target.closest('[data-detail]'),create=e.target.closest('[data-create]'),edit=e.target.closest('[data-edit]'),remove=e.target.closest('[data-delete]'),action=e.target.closest('[data-action]');if(page&&universe)navigate(page.dataset.page);if(detail&&universe)navigate(currentPage,detail.dataset.detail.split(':'));if(create&&universe)openModal(create.dataset.create);if(edit&&universe){const [t,id]=edit.dataset.edit.split(':');openModal(t,id)}if(remove&&confirm('Archive this entry?')){const[t,id]=remove.dataset.delete.split(':');universe[pluralFor(t)]=universe[pluralFor(t)].filter(x=>x.id!==id);navigate(t==='character'?'characters':'locations');persist('ENTRY ARCHIVED')}if(action?.dataset.action==='close-modal')$("#entityModal").hidden=true;if(action?.dataset.action==='edit-universe')openModal('universe')});
  $("#entityForm").addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),type=d.get('type');if(type==='universe'){universe.identity={...universe.identity,name:d.get('name').trim(),genre:d.get('subtitle').trim(),meta:d.get('meta').trim(),origin:d.get('origin').trim(),image:d.get('image').trim(),description:d.get('description').trim()};$("#entityModal").hidden=true;shell();navigate('universe');persist('UNIVERSE IDENTITY UPDATED');return}const list=universe[pluralFor(type)],id=d.get('id')||`${type[0]}${Date.now()}`,old=list.find(x=>x.id===id),item={...old,id,name:d.get('name').trim(),subtitle:d.get('subtitle').trim(),meta:d.get('meta').trim(),origin:d.get('origin').trim(),image:d.get('image').trim(),gallery:d.get('gallery').split('\n').map(x=>x.trim()).filter(Boolean).slice(0,8),description:d.get('description').trim()};old?Object.assign(old,item):list.unshift(item);$("#entityModal").hidden=true;navigate(type==='character'?'characters':'locations',[type,id]);persist(old?'ENTRY UPDATED':'NEW ENTRY DISCOVERED')});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')$("#entityModal").hidden=true});
  (async()=>{const saved=await desktop?.loadCredentials();if(saved){$("#owner").value=saved.owner;$("#repo").value=saved.repo;$("#token").value=saved.token;$("#remember").checked=true;$("#forgetButton").hidden=false}})();
}
